/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.libTAU4j.swig;

public class alert_notify_callback {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected alert_notify_callback(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(alert_notify_callback obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libTAU_jni.delete_alert_notify_callback(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    libTAU_jni.alert_notify_callback_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    libTAU_jni.alert_notify_callback_change_ownership(this, swigCPtr, true);
  }

  public void on_alert() {
    if (getClass() == alert_notify_callback.class) libTAU_jni.alert_notify_callback_on_alert(swigCPtr, this); else libTAU_jni.alert_notify_callback_on_alertSwigExplicitalert_notify_callback(swigCPtr, this);
  }

  public alert_notify_callback() {
    this(libTAU_jni.new_alert_notify_callback(), true);
    libTAU_jni.alert_notify_callback_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

}
