/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.libTAU4j.swig;

public class announce_endpoint {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected announce_endpoint(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(announce_endpoint obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libTAU_jni.delete_announce_endpoint(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public announce_endpoint() {
    this(libTAU_jni.new_announce_endpoint(), true);
  }

  public void setLocal_endpoint(tcp_endpoint value) {
    libTAU_jni.announce_endpoint_local_endpoint_set(swigCPtr, this, tcp_endpoint.getCPtr(value), value);
  }

  public tcp_endpoint getLocal_endpoint() {
    long cPtr = libTAU_jni.announce_endpoint_local_endpoint_get(swigCPtr, this);
    return (cPtr == 0) ? null : new tcp_endpoint(cPtr, false);
  }

  public void setEnabled(boolean value) {
    libTAU_jni.announce_endpoint_enabled_set(swigCPtr, this, value);
  }

  public boolean getEnabled() {
    return libTAU_jni.announce_endpoint_enabled_get(swigCPtr, this);
  }

  public announce_infohash get_infohash_v1() {
    return new announce_infohash(libTAU_jni.announce_endpoint_get_infohash_v1(swigCPtr, this), true);
  }

  public announce_infohash get_infohash_v2() {
    return new announce_infohash(libTAU_jni.announce_endpoint_get_infohash_v2(swigCPtr, this), true);
  }

}
