/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.libTAU4j.swig;

public class announce_entry_vector {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected announce_entry_vector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(announce_entry_vector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libTAU_jni.delete_announce_entry_vector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public announce_entry_vector() {
    this(libTAU_jni.new_announce_entry_vector__SWIG_0(), true);
  }

  public announce_entry_vector(long n) {
    this(libTAU_jni.new_announce_entry_vector__SWIG_1(n), true);
  }

  public long size() {
    return libTAU_jni.announce_entry_vector_size(swigCPtr, this);
  }

  public long capacity() {
    return libTAU_jni.announce_entry_vector_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    libTAU_jni.announce_entry_vector_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return libTAU_jni.announce_entry_vector_isEmpty(swigCPtr, this);
  }

  public void clear() {
    libTAU_jni.announce_entry_vector_clear(swigCPtr, this);
  }

  public void add(announce_entry x) {
    libTAU_jni.announce_entry_vector_add(swigCPtr, this, announce_entry.getCPtr(x), x);
  }

  public announce_entry get(int i) {
    return new announce_entry(libTAU_jni.announce_entry_vector_get(swigCPtr, this, i), false);
  }

  public void set(int i, announce_entry val) {
    libTAU_jni.announce_entry_vector_set(swigCPtr, this, i, announce_entry.getCPtr(val), val);
  }

}
