/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.libTAU4j.swig;

public class dht_error_alert extends alert {
  private transient long swigCPtr;

  protected dht_error_alert(long cPtr, boolean cMemoryOwn) {
    super(libTAU_jni.dht_error_alert_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(dht_error_alert obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libTAU_jni.delete_dht_error_alert(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public int type() {
    return libTAU_jni.dht_error_alert_type(swigCPtr, this);
  }

  public alert_category_t category() {
    return new alert_category_t(libTAU_jni.dht_error_alert_category(swigCPtr, this), true);
  }

  public String what() {
    return libTAU_jni.dht_error_alert_what(swigCPtr, this);
  }

  public String message() {
    return libTAU_jni.dht_error_alert_message(swigCPtr, this);
  }

  public void setError(error_code value) {
    libTAU_jni.dht_error_alert_error_set(swigCPtr, this, error_code.getCPtr(value), value);
  }

  public error_code getError() {
    long cPtr = libTAU_jni.dht_error_alert_error_get(swigCPtr, this);
    return (cPtr == 0) ? null : new error_code(cPtr, false);
  }

  public void setOp(operation_t value) {
    libTAU_jni.dht_error_alert_op_set(swigCPtr, this, value.swigValue());
  }

  public operation_t getOp() {
    return operation_t.swigToEnum(libTAU_jni.dht_error_alert_op_get(swigCPtr, this));
  }

  public final static alert_priority priority = alert_priority.swigToEnum(libTAU_jni.dht_error_alert_priority_get());
  public final static int alert_type = libTAU_jni.dht_error_alert_alert_type_get();
  public final static alert_category_t static_category = new alert_category_t(libTAU_jni.dht_error_alert_static_category_get(), false);
}
