/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.libTAU4j.swig;

public class ip_interface {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ip_interface(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ip_interface obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libTAU_jni.delete_ip_interface(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setInterface_address(address value) {
    libTAU_jni.ip_interface_interface_address_set(swigCPtr, this, address.getCPtr(value), value);
  }

  public address getInterface_address() {
    long cPtr = libTAU_jni.ip_interface_interface_address_get(swigCPtr, this);
    return (cPtr == 0) ? null : new address(cPtr, false);
  }

  public void setNetmask(address value) {
    libTAU_jni.ip_interface_netmask_set(swigCPtr, this, address.getCPtr(value), value);
  }

  public address getNetmask() {
    long cPtr = libTAU_jni.ip_interface_netmask_get(swigCPtr, this);
    return (cPtr == 0) ? null : new address(cPtr, false);
  }

  public void setName(byte_vector value) {
    libTAU_jni.ip_interface_name_set(swigCPtr, this, byte_vector.getCPtr(value), value);
  }

  public byte_vector getName() {
    long cPtr = libTAU_jni.ip_interface_name_get(swigCPtr, this);
    return (cPtr == 0) ? null : new byte_vector(cPtr, false);
  }

  public void setFriendly_name(byte_vector value) {
    libTAU_jni.ip_interface_friendly_name_set(swigCPtr, this, byte_vector.getCPtr(value), value);
  }

  public byte_vector getFriendly_name() {
    long cPtr = libTAU_jni.ip_interface_friendly_name_get(swigCPtr, this);
    return (cPtr == 0) ? null : new byte_vector(cPtr, false);
  }

  public void setDescription(byte_vector value) {
    libTAU_jni.ip_interface_description_set(swigCPtr, this, byte_vector.getCPtr(value), value);
  }

  public byte_vector getDescription() {
    long cPtr = libTAU_jni.ip_interface_description_get(swigCPtr, this);
    return (cPtr == 0) ? null : new byte_vector(cPtr, false);
  }

  public void setPreferred(boolean value) {
    libTAU_jni.ip_interface_preferred_set(swigCPtr, this, value);
  }

  public boolean getPreferred() {
    return libTAU_jni.ip_interface_preferred_get(swigCPtr, this);
  }

  public ip_interface() {
    this(libTAU_jni.new_ip_interface(), true);
  }

}
