/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.libTAU4j.swig;

public class message {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected message(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(message obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libTAU_jni.delete_message(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public message() {
    this(libTAU_jni.new_message__SWIG_0(), true);
  }

  public message(entry e) {
    this(libTAU_jni.new_message__SWIG_1(entry.getCPtr(e), e), true);
  }

  public message(String encode) {
    this(libTAU_jni.new_message__SWIG_2(encode), true);
  }

  public long timestamp() {
    return libTAU_jni.message_timestamp(swigCPtr, this);
  }

  public entry get_entry() {
    return new entry(libTAU_jni.message_get_entry(swigCPtr, this), true);
  }

  public String encode() {
    return libTAU_jni.message_encode(swigCPtr, this);
  }

  public sha256_hash sha256() {
    return new sha256_hash(libTAU_jni.message_sha256(swigCPtr, this), true);
  }

  public String to_string() {
    return libTAU_jni.message_to_string(swigCPtr, this);
  }

  public boolean empty() {
    return libTAU_jni.message_empty(swigCPtr, this);
  }

  public boolean eq(message rhs) {
    return libTAU_jni.message_eq(swigCPtr, this, message.getCPtr(rhs), rhs);
  }

  public boolean ne(message rhs) {
    return libTAU_jni.message_ne(swigCPtr, this, message.getCPtr(rhs), rhs);
  }

  public boolean lt(message rhs) {
    return libTAU_jni.message_lt(swigCPtr, this, message.getCPtr(rhs), rhs);
  }

  public boolean gt(message rhs) {
    return libTAU_jni.message_gt(swigCPtr, this, message.getCPtr(rhs), rhs);
  }

  public boolean lte(message rhs) {
    return libTAU_jni.message_lte(swigCPtr, this, message.getCPtr(rhs), rhs);
  }

  public boolean gte(message rhs) {
    return libTAU_jni.message_gte(swigCPtr, this, message.getCPtr(rhs), rhs);
  }

}
