/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.libTAU4j.swig;

public class piece_block_vector {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected piece_block_vector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(piece_block_vector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libTAU_jni.delete_piece_block_vector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public piece_block_vector() {
    this(libTAU_jni.new_piece_block_vector__SWIG_0(), true);
  }

  public piece_block_vector(long n) {
    this(libTAU_jni.new_piece_block_vector__SWIG_1(n), true);
  }

  public long size() {
    return libTAU_jni.piece_block_vector_size(swigCPtr, this);
  }

  public long capacity() {
    return libTAU_jni.piece_block_vector_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    libTAU_jni.piece_block_vector_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return libTAU_jni.piece_block_vector_isEmpty(swigCPtr, this);
  }

  public void clear() {
    libTAU_jni.piece_block_vector_clear(swigCPtr, this);
  }

  public void add(piece_block x) {
    libTAU_jni.piece_block_vector_add(swigCPtr, this, piece_block.getCPtr(x), x);
  }

  public piece_block get(int i) {
    return new piece_block(libTAU_jni.piece_block_vector_get(swigCPtr, this, i), false);
  }

  public void set(int i, piece_block val) {
    libTAU_jni.piece_block_vector_set(swigCPtr, this, i, piece_block.getCPtr(val), val);
  }

}
