/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.libTAU4j.swig;

public class set_piece_hashes_listener {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected set_piece_hashes_listener(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(set_piece_hashes_listener obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libTAU_jni.delete_set_piece_hashes_listener(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    libTAU_jni.set_piece_hashes_listener_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    libTAU_jni.set_piece_hashes_listener_change_ownership(this, swigCPtr, true);
  }

  public void progress(int i) {
    if (getClass() == set_piece_hashes_listener.class) libTAU_jni.set_piece_hashes_listener_progress(swigCPtr, this, i); else libTAU_jni.set_piece_hashes_listener_progressSwigExplicitset_piece_hashes_listener(swigCPtr, this, i);
  }

  public set_piece_hashes_listener() {
    this(libTAU_jni.new_set_piece_hashes_listener(), true);
    libTAU_jni.set_piece_hashes_listener_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

}
