/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.libTAU4j.swig;

public class sha1_hash_vector {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected sha1_hash_vector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(sha1_hash_vector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libTAU_jni.delete_sha1_hash_vector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public sha1_hash_vector() {
    this(libTAU_jni.new_sha1_hash_vector__SWIG_0(), true);
  }

  public sha1_hash_vector(long n) {
    this(libTAU_jni.new_sha1_hash_vector__SWIG_1(n), true);
  }

  public long size() {
    return libTAU_jni.sha1_hash_vector_size(swigCPtr, this);
  }

  public long capacity() {
    return libTAU_jni.sha1_hash_vector_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    libTAU_jni.sha1_hash_vector_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return libTAU_jni.sha1_hash_vector_isEmpty(swigCPtr, this);
  }

  public void clear() {
    libTAU_jni.sha1_hash_vector_clear(swigCPtr, this);
  }

  public void add(sha1_hash x) {
    libTAU_jni.sha1_hash_vector_add(swigCPtr, this, sha1_hash.getCPtr(x), x);
  }

  public sha1_hash get(int i) {
    return new sha1_hash(libTAU_jni.sha1_hash_vector_get(swigCPtr, this, i), false);
  }

  public void set(int i, sha1_hash val) {
    libTAU_jni.sha1_hash_vector_set(swigCPtr, this, i, sha1_hash.getCPtr(val), val);
  }

}
