/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.libTAU4j.swig;

public class stats_metric_vector {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected stats_metric_vector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(stats_metric_vector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libTAU_jni.delete_stats_metric_vector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public stats_metric_vector() {
    this(libTAU_jni.new_stats_metric_vector__SWIG_0(), true);
  }

  public stats_metric_vector(long n) {
    this(libTAU_jni.new_stats_metric_vector__SWIG_1(n), true);
  }

  public long size() {
    return libTAU_jni.stats_metric_vector_size(swigCPtr, this);
  }

  public long capacity() {
    return libTAU_jni.stats_metric_vector_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    libTAU_jni.stats_metric_vector_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return libTAU_jni.stats_metric_vector_isEmpty(swigCPtr, this);
  }

  public void clear() {
    libTAU_jni.stats_metric_vector_clear(swigCPtr, this);
  }

  public void add(stats_metric x) {
    libTAU_jni.stats_metric_vector_add(swigCPtr, this, stats_metric.getCPtr(x), x);
  }

  public stats_metric get(int i) {
    return new stats_metric(libTAU_jni.stats_metric_vector_get(swigCPtr, this, i), false);
  }

  public void set(int i, stats_metric val) {
    libTAU_jni.stats_metric_vector_set(swigCPtr, this, i, stats_metric.getCPtr(val), val);
  }

}
