/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.libTAU4j.swig;

public class string_string_map {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected string_string_map(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(string_string_map obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libTAU_jni.delete_string_string_map(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public string_string_map() {
    this(libTAU_jni.new_string_string_map__SWIG_0(), true);
  }

  public string_string_map(string_string_map arg0) {
    this(libTAU_jni.new_string_string_map__SWIG_1(string_string_map.getCPtr(arg0), arg0), true);
  }

  public long size() {
    return libTAU_jni.string_string_map_size(swigCPtr, this);
  }

  public boolean empty() {
    return libTAU_jni.string_string_map_empty(swigCPtr, this);
  }

  public void clear() {
    libTAU_jni.string_string_map_clear(swigCPtr, this);
  }

  public String get(String key) {
    return libTAU_jni.string_string_map_get(swigCPtr, this, key);
  }

  public void set(String key, String x) {
    libTAU_jni.string_string_map_set(swigCPtr, this, key, x);
  }

  public void del(String key) {
    libTAU_jni.string_string_map_del(swigCPtr, this, key);
  }

  public boolean has_key(String key) {
    return libTAU_jni.string_string_map_has_key(swigCPtr, this, key);
  }

}
