/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.libTAU4j.swig;

public class string_string_pair {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected string_string_pair(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(string_string_pair obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libTAU_jni.delete_string_string_pair(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public string_string_pair() {
    this(libTAU_jni.new_string_string_pair__SWIG_0(), true);
  }

  public string_string_pair(String first, String second) {
    this(libTAU_jni.new_string_string_pair__SWIG_1(first, second), true);
  }

  public string_string_pair(string_string_pair p) {
    this(libTAU_jni.new_string_string_pair__SWIG_2(string_string_pair.getCPtr(p), p), true);
  }

  public void setFirst(String value) {
    libTAU_jni.string_string_pair_first_set(swigCPtr, this, value);
  }

  public String getFirst() {
    return libTAU_jni.string_string_pair_first_get(swigCPtr, this);
  }

  public void setSecond(String value) {
    libTAU_jni.string_string_pair_second_set(swigCPtr, this, value);
  }

  public String getSecond() {
    return libTAU_jni.string_string_pair_second_get(swigCPtr, this);
  }

}
