/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.libTAU4j.swig;

public class udp_endpoint_vector {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected udp_endpoint_vector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(udp_endpoint_vector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libTAU_jni.delete_udp_endpoint_vector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public udp_endpoint_vector() {
    this(libTAU_jni.new_udp_endpoint_vector__SWIG_0(), true);
  }

  public udp_endpoint_vector(long n) {
    this(libTAU_jni.new_udp_endpoint_vector__SWIG_1(n), true);
  }

  public long size() {
    return libTAU_jni.udp_endpoint_vector_size(swigCPtr, this);
  }

  public long capacity() {
    return libTAU_jni.udp_endpoint_vector_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    libTAU_jni.udp_endpoint_vector_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return libTAU_jni.udp_endpoint_vector_isEmpty(swigCPtr, this);
  }

  public void clear() {
    libTAU_jni.udp_endpoint_vector_clear(swigCPtr, this);
  }

  public void add(udp_endpoint x) {
    libTAU_jni.udp_endpoint_vector_add(swigCPtr, this, udp_endpoint.getCPtr(x), x);
  }

  public udp_endpoint get(int i) {
    return new udp_endpoint(libTAU_jni.udp_endpoint_vector_get(swigCPtr, this, i), false);
  }

  public void set(int i, udp_endpoint val) {
    libTAU_jni.udp_endpoint_vector_set(swigCPtr, this, i, udp_endpoint.getCPtr(val), val);
  }

}
