/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.libTAU4j.swig;

public class unsigned_byte_array_32 {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected unsigned_byte_array_32(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(unsigned_byte_array_32 obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libTAU_jni.delete_unsigned_byte_array_32(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public unsigned_byte_array_32() {
    this(libTAU_jni.new_unsigned_byte_array_32__SWIG_0(), true);
  }

  public unsigned_byte_array_32(unsigned_byte_array_32 other) {
    this(libTAU_jni.new_unsigned_byte_array_32__SWIG_1(unsigned_byte_array_32.getCPtr(other), other), true);
  }

  public long size() {
    return libTAU_jni.unsigned_byte_array_32_size(swigCPtr, this);
  }

  public boolean isEmpty() {
    return libTAU_jni.unsigned_byte_array_32_isEmpty(swigCPtr, this);
  }

  public void fill(short u) {
    libTAU_jni.unsigned_byte_array_32_fill(swigCPtr, this, u);
  }

  public short get(int i) {
    return libTAU_jni.unsigned_byte_array_32_get(swigCPtr, this, i);
  }

  public void set(int i, short val) {
    libTAU_jni.unsigned_byte_array_32_set(swigCPtr, this, i, val);
  }

}
