/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.libTAU4j.swig;

public class vector_unsigned_byte_array_32 {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected vector_unsigned_byte_array_32(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(vector_unsigned_byte_array_32 obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libTAU_jni.delete_vector_unsigned_byte_array_32(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public vector_unsigned_byte_array_32() {
    this(libTAU_jni.new_vector_unsigned_byte_array_32__SWIG_0(), true);
  }

  public vector_unsigned_byte_array_32(long n) {
    this(libTAU_jni.new_vector_unsigned_byte_array_32__SWIG_1(n), true);
  }

  public long size() {
    return libTAU_jni.vector_unsigned_byte_array_32_size(swigCPtr, this);
  }

  public long capacity() {
    return libTAU_jni.vector_unsigned_byte_array_32_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    libTAU_jni.vector_unsigned_byte_array_32_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return libTAU_jni.vector_unsigned_byte_array_32_isEmpty(swigCPtr, this);
  }

  public void clear() {
    libTAU_jni.vector_unsigned_byte_array_32_clear(swigCPtr, this);
  }

  public void add(unsigned_byte_array_32 x) {
    libTAU_jni.vector_unsigned_byte_array_32_add(swigCPtr, this, unsigned_byte_array_32.getCPtr(x), x);
  }

  public unsigned_byte_array_32 get(int i) {
    return new unsigned_byte_array_32(libTAU_jni.vector_unsigned_byte_array_32_get(swigCPtr, this, i), false);
  }

  public void set(int i, unsigned_byte_array_32 val) {
    libTAU_jni.vector_unsigned_byte_array_32_set(swigCPtr, this, i, unsigned_byte_array_32.getCPtr(val), val);
  }

}
