/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.libtorrent4j.swig;

public class bool_vector_vector {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected bool_vector_vector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(bool_vector_vector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libtorrent_jni.delete_bool_vector_vector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public bool_vector_vector() {
    this(libtorrent_jni.new_bool_vector_vector__SWIG_0(), true);
  }

  public bool_vector_vector(long n) {
    this(libtorrent_jni.new_bool_vector_vector__SWIG_1(n), true);
  }

  public long size() {
    return libtorrent_jni.bool_vector_vector_size(swigCPtr, this);
  }

  public long capacity() {
    return libtorrent_jni.bool_vector_vector_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    libtorrent_jni.bool_vector_vector_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return libtorrent_jni.bool_vector_vector_isEmpty(swigCPtr, this);
  }

  public void clear() {
    libtorrent_jni.bool_vector_vector_clear(swigCPtr, this);
  }

  public void add(bool_vector x) {
    libtorrent_jni.bool_vector_vector_add(swigCPtr, this, bool_vector.getCPtr(x), x);
  }

  public bool_vector get(int i) {
    return new bool_vector(libtorrent_jni.bool_vector_vector_get(swigCPtr, this, i), false);
  }

  public void set(int i, bool_vector val) {
    libtorrent_jni.bool_vector_vector_set(swigCPtr, this, i, bool_vector.getCPtr(val), val);
  }

}
