/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.libtorrent4j.swig;

public class sha256_hash_udp_endpoint_pair_vector {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected sha256_hash_udp_endpoint_pair_vector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(sha256_hash_udp_endpoint_pair_vector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libtorrent_jni.delete_sha256_hash_udp_endpoint_pair_vector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public sha256_hash_udp_endpoint_pair_vector() {
    this(libtorrent_jni.new_sha256_hash_udp_endpoint_pair_vector__SWIG_0(), true);
  }

  public sha256_hash_udp_endpoint_pair_vector(long n) {
    this(libtorrent_jni.new_sha256_hash_udp_endpoint_pair_vector__SWIG_1(n), true);
  }

  public long size() {
    return libtorrent_jni.sha256_hash_udp_endpoint_pair_vector_size(swigCPtr, this);
  }

  public long capacity() {
    return libtorrent_jni.sha256_hash_udp_endpoint_pair_vector_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    libtorrent_jni.sha256_hash_udp_endpoint_pair_vector_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return libtorrent_jni.sha256_hash_udp_endpoint_pair_vector_isEmpty(swigCPtr, this);
  }

  public void clear() {
    libtorrent_jni.sha256_hash_udp_endpoint_pair_vector_clear(swigCPtr, this);
  }

  public void add(sha256_hash_udp_endpoint_pair x) {
    libtorrent_jni.sha256_hash_udp_endpoint_pair_vector_add(swigCPtr, this, sha256_hash_udp_endpoint_pair.getCPtr(x), x);
  }

  public sha256_hash_udp_endpoint_pair get(int i) {
    return new sha256_hash_udp_endpoint_pair(libtorrent_jni.sha256_hash_udp_endpoint_pair_vector_get(swigCPtr, this, i), false);
  }

  public void set(int i, sha256_hash_udp_endpoint_pair val) {
    libtorrent_jni.sha256_hash_udp_endpoint_pair_vector_set(swigCPtr, this, i, sha256_hash_udp_endpoint_pair.getCPtr(val), val);
  }

}
